name: Bulk import repos pipeline

on:
  workflow_dispatch:

jobs:
  bulk-import-repos:
    uses: ljubon-org/github-terraformer/.github/workflows/bulk-import.yaml@test-env
    with:
      gcss_ref: test-env
    secrets:
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
