name: Bulk import repos pipeline

on:
  workflow_dispatch:

jobs:
  bulk-import-repos:
    uses: ljubon-org/github-terraformer/.github/workflows/bulk-import.yaml@fix-empty-state-import
    with:
      gcss_ref: fix-empty-state-import
    secrets:
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
