name: "Drift Check"

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  drift-check:
    secrets:
      tfc_token: ${{ secrets.TFC_TOKEN }}
    uses: ljubon-org/github-terraformer/.github/workflows/drift-check.yaml@fix-empty-state-import
    with:
      gcss_ref: fix-empty-state-import
      tfc_org: "ljubo-demo" # FIXME: now
