name: Terraform apply

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'importer_tmp_dir/**'

jobs:
  terraform-apply:
    uses: ljubon-org/github-terraformer/.github/workflows/tf-apply.yaml@test-env
    with:
      commit_sha: ${{ github.sha }}
      gcss_ref: test-env
      tfc_org: "ljubo-demo" # FIXME: now
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      tfc_token: ${{ secrets.TFC_TOKEN }}
