name: Terraform Plan

on:
  workflow_run:
    workflows: [ "Bootstrap" ]
    types:
      - requested

jobs:
  terraform-plan:
    uses: ljubon-org/github-terraformer/.github/workflows/tf-plan.yaml@set-public-provider
    with:
      commit_sha: ${{ github.event.workflow_run.head_sha }}
      gcss_ref: set-public-provider
      tfc_org: "ljubo-demo" # FIXME:
    secrets:
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      tfc_token: ${{ secrets.TFC_TOKEN }}
